spring:
  application:
    name: atom-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

# 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file:
    path: ./logs/app

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deletedTime
      logic-delete-value: now()
      logic-not-delete-value: 'null'
  mapper-locations: classpath*:mapper/**/*.xml

# 线程池配置
task:
  executor:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 100
    keep-alive-seconds: 60
    thread-name-prefix: atom-demo-task-
