######################## 生产环境使用 ####################
spring:
  application:
    name: ${rootArtifactId}
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

# 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file:
    path: ./logs/app

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deletedTime
      logic-delete-value: now()
      logic-not-delete-value: 'null'
  mapper-locations: classpath*:mapper/**/*.xml

# 线程池配置
task:
  executor:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 100
    keep-alive-seconds: 60
    thread-name-prefix: ${artifactId}-task-
