version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: atom-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: atom_db
      MYSQL_USER: atom_user
      MYSQL_PASSWORD: atom_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - atom-network

  redis:
    image: redis:7-alpine
    container_name: atom-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - atom-network

volumes:
  mysql_data:
  redis_data:

networks:
  atom-network:
    driver: bridge
